koda:
  frontend:
    url: http://localhost:5173
  offer:
    photos-path: file:///C:/wapro-baza/FOTKI_SKLEP/
  security:
    jwt:
      secret-key: baf1e39a8c58425f98c9dce83abe581fd7ad3ce76984c5f48cc9f781dcf30d47ba9c7e862548412dabc851f8bf26e903
      access-expiration: 1209600000

spring:
  application:
    name: koda-backend
  liquibase:
    change-log: classpath:liquibase/changeLog.yaml
    enabled: true
    clear-checksums: true
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:6001/kodadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8137

management:
  endpoints:
    web:
      exposure:
        include: mappings
  endpoint:
    mappings:
      enabled: true
